export const TASK_CENTER_COPY = {
  missingProjectId: "缺少 projectId",
  loading: "加载中...",
  processing: "处理中...",
  allOption: "全部",
  refresh: "刷新",
  requestIdCopyTitle: "复制失败：请手动复制请求 ID（request_id）",
  runIdCopyTitle: "复制失败：请手动复制 run_id",
  copyDebugInfoTitle: "Copy debug info manually",
  cancelQueuedProjectTaskConfirm: "确认取消该排队中的任务？取消后将不会执行。",
  cancelBatchConfirm: "确认取消当前批处理任务？取消后本批不会继续执行。",
  unknownErrorType: "ERROR",
  unknownErrorMessage: "未知错误",

  queueStatusAria: "队列状态 (taskcenter_queue_status)",
  queueBackendLabel: "配置后端（queue_backend）",
  effectiveBackendLabel: "实际后端（effective_backend）",
  redisOkLabel: "redis_ok",
  queueNameLabel: "queue",
  queueInlineWarning: "提示：inline 为进程内单线程 worker，任务会排队串行执行；如需并发请启动 rq+worker。",
  queueHealthCopyButton: "复制 health 请求 ID（request_id）",

  usageLinksPrefix: "常用入口：",
  helpStructuredMemory: "结构化记忆",
  helpWriting: "写作页",
  helpUsageSuffix: "之间来回跳转，查看“提议→应用→回滚”的全链路。",

  changeSetsSectionAria: "变更集 (taskcenter_changesets_section)",
  changeSetsTitle: "变更集（Change Set）",
  changeSetsHint: "按状态筛选；点击条目查看摘要与原始数据（默认折叠）",
  changeSetsStatusHint: "状态说明：未应用=仅提议 | 已应用=已落库 | 已回滚=已撤销 | 失败=执行异常",
  changeSetsEmpty: "暂无变更集",
  changeSetsStatusLabel: "状态",
  countLabels: {
    all: "总计",
    queued: "排队中",
    running: "运行中",
    done: "完成",
    failed: "失败",
  },
  changeSetsCounts: {
    all: "总计",
    proposed: "未应用",
    applied: "已应用",
    rolledBack: "已回滚",
    failed: "失败",
  },

  tasksSectionAria: "任务列表 (taskcenter_tasks_section)",
  tasksTitle: "任务（Task）",
  tasksHintPrefix: "失败任务会显示错误摘要与 ",
  tasksStatusHint: "状态说明：排队中→运行中→完成/失败（如失败可用 request_id 查后端日志）",
  tasksEmpty: "暂无任务",
  tasksFailedOnly: "仅看失败",

  projectTasksSectionAria: "项目任务 (taskcenter_projecttasks_section)",
  projectTasksTitle: "项目任务（Project Task）",
  projectTasksHint:
    "用于 worldbook/search/vector/graph 等自动化后台更新；点击条目查看详情（params/result/error 已脱敏）",
  projectTasksStatusHint: "状态说明：排队中→运行中→完成/失败",
  projectTasksLiveStatusPrefix: "Project SSE: ",
  projectTasksLiveLabels: {
    idle: "idle",
    connecting: "reconnecting",
    open: "connected",
    error: "fallback polling",
  },
  projectTasksEmpty: "暂无项目任务",
  projectTasksFailedOnly: "仅看失败",
  projectTasksRetry: "重试",
  projectTasksCancel: "取消",
  projectTasksRetryToast: "已重试任务",
  projectTasksCancelToast: "已取消任务",
  projectTasksIdempotencyPrefix: "幂等键：",

  detailCopyDebug: "复制 Debug 信息",
  detailClose: "关闭",
  detailOverview: "Overview",
  detailActions: "Actions",
  detailGenerationRun: "GenerationRun",
  detailError: "Error",
  detailChangeSet: "ChangeSet",
  detailResults: "Results",
  detailRawJson: "原始数据（JSON）",
  detailNoError: "无错误信息",
  detailMissingChangeSet: "该任务 result 未包含 change_set（可能仍在运行或已失败）。",
  detailApplyRollbackHint: "提示：Apply/Rollback 需要 editor 权限；失败时可复制 request_id 排障。",
  detailRefreshProjectTask: "刷新详情",
  detailApplyChangeSetToast: "已应用 ChangeSet",
  detailRollbackChangeSetToast: "已回滚 ChangeSet",

  requestIdCopyButton: "复制请求 ID（request_id）",
  projectTaskRunIdCopyButton: "复制 run_id",
  projectTaskRunIdOpenButton: "打开运行记录",
  applyChangeSetButton: "Apply",
  rollbackChangeSetButton: "Rollback",

  runtimeTitle: "Runtime",
  runtimeRefreshButton: "Refresh runtime",
  runtimeEmpty: "No unified runtime data yet.",
  runtimeBatchTitle: "Batch",
  runtimeArtifactsTitle: "Artifacts",
  runtimeTimelineTitle: "Timeline",
  runtimeNoBatchItems: "No batch steps yet.",
  runtimeNoTimeline: "No timeline events yet.",
  runtimeOpenGenerationRun: "Open generation run",
  runtimeBatchPause: "Pause",
  runtimeBatchResume: "Resume",
  runtimeBatchRetryFailed: "Retry failed chapters",
  runtimeBatchSkipFailed: "Skip failed chapters",
  runtimeBatchCancel: "Cancel batch",
  runtimeBatchWorking: "Working...",
  runtimeBatchPausedToast: "Batch paused.",
  runtimeBatchResumedToast: "Batch resumed.",
  runtimeBatchRetryFailedToast: "Failed chapters queued for retry.",
  runtimeBatchSkipFailedToast: "Failed chapters skipped.",
  runtimeBatchCanceledToast: "Batch canceled.",
} as const;
