name: novel_agent_adapters
description: Adapter implementations for NovelAgent.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.9.0

dependencies:
  archive: ^3.6.1
  fast_gbk: ^1.0.0
  novel_agent_core:
    path: ../novel_agent_core
  sqlite3: ^2.7.7

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8
