"""add project tables

Revision ID: 026e378fe453
Revises: 33aadf6df492
Create Date: 2026-01-25 05:10:23.293587

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "026e378fe453"
down_revision = "33aadf6df492"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_tables",
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('table_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('schema_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'table_key', name='uq_project_tables_project_id_table_key')
    )
    with op.batch_alter_table('project_tables', schema=None) as batch_op:
        batch_op.create_index('ix_project_tables_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_project_tables_project_id_table_key', ['project_id', 'table_key'], unique=False)

    op.create_table(
        "project_table_rows",
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['project_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_table_rows', schema=None) as batch_op:
        batch_op.create_index('ix_project_table_rows_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_project_table_rows_table_id', ['table_id'], unique=False)
        batch_op.create_index('ix_project_table_rows_table_id_row_index', ['table_id', 'row_index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_table_rows', schema=None) as batch_op:
        batch_op.drop_index('ix_project_table_rows_table_id_row_index')
        batch_op.drop_index('ix_project_table_rows_table_id')
        batch_op.drop_index('ix_project_table_rows_project_id')

    op.drop_table('project_table_rows')
    with op.batch_alter_table('project_tables', schema=None) as batch_op:
        batch_op.drop_index('ix_project_tables_project_id_table_key')
        batch_op.drop_index('ix_project_tables_project_id')

    op.drop_table('project_tables')
    # ### end Alembic commands ###
