"""init

Revision ID: 0f24b611cf21
Revises: 
Create Date: 2025-12-13 00:20:18.758507

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0f24b611cf21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('logline', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_owner_user_id', ['owner_user_id'], unique=False)

    op.create_table('chapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_chapters_project_id_number')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index('ix_chapters_project_id', ['project_id'], unique=False)

    op.create_table('characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index('ix_characters_project_id', ['project_id'], unique=False)

    op.create_table('llm_presets',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('presence_penalty', sa.Float(), nullable=True),
    sa.Column('frequency_penalty', sa.Float(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('stop_json', sa.Text(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('outline',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_settings',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('world_setting', sa.Text(), nullable=True),
    sa.Column('style_guide', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('system_template', sa.Text(), nullable=True),
    sa.Column('user_template', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'type', name='uq_prompt_templates_project_id_type')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index('ix_prompt_templates_project_id', ['project_id'], unique=False)

    op.create_table('generation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_system', sa.Text(), nullable=True),
    sa.Column('prompt_user', sa.Text(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.create_index('ix_generation_runs_project_id', ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_generation_runs_project_id')

    op.drop_table('generation_runs')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_templates_project_id')

    op.drop_table('prompt_templates')
    op.drop_table('project_settings')
    op.drop_table('outline')
    op.drop_table('llm_presets')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index('ix_characters_project_id')

    op.drop_table('characters')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index('ix_chapters_project_id')

    op.drop_table('chapters')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_owner_user_id')

    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
