"""add_project_tasks

Revision ID: 4c971683d6cb
Revises: ee23bd2770fc
Create Date: 2026-01-30 17:15:16.956987

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4c971683d6cb'
down_revision = 'ee23bd2770fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_project_tasks_project_idempotency_key')
    )
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_project_tasks_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_project_tasks_project_id_kind', ['project_id', 'kind'], unique=False)
        batch_op.create_index('ix_project_tasks_project_id_status', ['project_id', 'status'], unique=False)
        batch_op.create_index('ix_project_tasks_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_project_tasks_status')
        batch_op.drop_index('ix_project_tasks_project_id_status')
        batch_op.drop_index('ix_project_tasks_project_id_kind')
        batch_op.drop_index('ix_project_tasks_project_id')

    op.drop_table('project_tasks')
    # ### end Alembic commands ###
