"""add worldbook entries

Revision ID: 76954388cbe7
Revises: 09e76a9bafd4
Create Date: 2026-01-09 23:57:24.358534

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '76954388cbe7'
down_revision = '09e76a9bafd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worldbook_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('constant', sa.Boolean(), nullable=False),
    sa.Column('keywords_json', sa.Text(), nullable=True),
    sa.Column('exclude_recursion', sa.Boolean(), nullable=False),
    sa.Column('prevent_recursion', sa.Boolean(), nullable=False),
    sa.Column('char_limit', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worldbook_entries', schema=None) as batch_op:
        batch_op.create_index('ix_worldbook_entries_project_id_constant_enabled', ['project_id', 'constant', 'enabled'], unique=False)
        batch_op.create_index('ix_worldbook_entries_project_id_enabled', ['project_id', 'enabled'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worldbook_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_worldbook_entries_project_id_enabled')
        batch_op.drop_index('ix_worldbook_entries_project_id_constant_enabled')

    op.drop_table('worldbook_entries')
    # ### end Alembic commands ###
