"""add project source documents

Revision ID: d8ffc3ff79f5
Revises: 714c1b58c136
Create Date: 2026-01-25 09:29:29.756883

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd8ffc3ff79f5'
down_revision = '714c1b58c136'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_source_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('progress_message', sa.String(length=255), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.String(length=64), nullable=True),
    sa.Column('vector_ingest_result_json', sa.Text(), nullable=True),
    sa.Column('worldbook_proposal_json', sa.Text(), nullable=True),
    sa.Column('story_memory_proposal_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_source_documents', schema=None) as batch_op:
        batch_op.create_index('ix_project_source_documents_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_project_source_documents_status', ['status'], unique=False)

    op.create_table('project_source_document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('vector_chunk_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['project_source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_project_source_document_chunks_document_index')
    )
    with op.batch_alter_table('project_source_document_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_project_source_document_chunks_document_id', ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_source_document_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_project_source_document_chunks_document_id')

    op.drop_table('project_source_document_chunks')
    with op.batch_alter_table('project_source_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_project_source_documents_status')
        batch_op.drop_index('ix_project_source_documents_project_id')

    op.drop_table('project_source_documents')
    # ### end Alembic commands ###
