"""add glossary terms

Revision ID: ee23bd2770fc
Revises: d8ffc3ff79f5
Create Date: 2026-01-25 10:56:22.293719

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ee23bd2770fc'
down_revision = 'd8ffc3ff79f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_terms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('aliases_json', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'term', name='uq_glossary_terms_project_term')
    )
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.create_index('ix_glossary_terms_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_glossary_terms_term', ['term'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.drop_index('ix_glossary_terms_term')
        batch_op.drop_index('ix_glossary_terms_project_id')

    op.drop_table('glossary_terms')
    # ### end Alembic commands ###
